// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: outbox.sql

package queries

import (
	"context"
	"time"
)

const deletePublished = `-- name: DeletePublished :execrows
DELETE FROM core.outbox
WHERE published_at < $1
`

func (q *Queries) DeletePublished(ctx context.Context, publishedBefore *time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, deletePublished, publishedBefore)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const enqueue = `-- name: Enqueue :exec
INSERT INTO core.outbox (topic, message_key, payload, headers)
VALUES ($1, $2, $3, $4)
`

type EnqueueParams struct {
	Topic      string
	MessageKey string
	Payload    []byte
	Headers    []byte
}

func (q *Queries) Enqueue(ctx context.Context, arg EnqueueParams) error {
	_, err := q.db.Exec(ctx, enqueue,
		arg.Topic,
		arg.MessageKey,
		arg.Payload,
		arg.Headers,
	)
	return err
}

const listPending = `-- name: ListPending :many
SELECT
    id,
    topic,
    message_key,
    payload,
    headers
FROM core.outbox
WHERE published_at IS NULL
ORDER BY id
LIMIT $1
FOR UPDATE
`

type ListPendingRow struct {
	ID         int64
	Topic      string
	MessageKey string
	Payload    []byte
	Headers    []byte
}

func (q *Queries) ListPending(ctx context.Context, rowLimit int32) ([]ListPendingRow, error) {
	rows, err := q.db.Query(ctx, listPending, rowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPendingRow
	for rows.Next() {
		var i ListPendingRow
		if err := rows.Scan(
			&i.ID,
			&i.Topic,
			&i.MessageKey,
			&i.Payload,
			&i.Headers,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markPublished = `-- name: MarkPublished :exec
UPDATE core.outbox
SET published_at = $1
WHERE id = ANY ($2::bigint[])
`

type MarkPublishedParams struct {
	PublishedAt *time.Time
	Ids         []int64
}

func (q *Queries) MarkPublished(ctx context.Context, arg MarkPublishedParams) error {
	_, err := q.db.Exec(ctx, markPublished, arg.PublishedAt, arg.Ids)
	return err
}

const tryLockRelay = `-- name: TryLockRelay :one
SELECT pg_try_advisory_xact_lock(4715400003)
`

// One relay publishes at a time, so messages reach Kafka in outbox order.
func (q *Queries) TryLockRelay(ctx context.Context) (bool, error) {
	row := q.db.QueryRow(ctx, tryLockRelay)
	var pg_try_advisory_xact_lock bool
	err := row.Scan(&pg_try_advisory_xact_lock)
	return pg_try_advisory_xact_lock, err
}
