// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package queries

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO core.users (
    tenant_id,
    email,
    password_hash,
    full_name,
    phone,
    role
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
RETURNING
    id,
    email,
    full_name,
    phone,
    role,
    is_active,
    last_login_at,
    created_at,
    updated_at
`

type CreateUserParams struct {
	TenantID     uuid.UUID
	Email        string
	PasswordHash string
	FullName     string
	Phone        *string
	Role         string
}

type CreateUserRow struct {
	ID          uuid.UUID
	Email       string
	FullName    string
	Phone       *string
	Role        string
	IsActive    bool
	LastLoginAt *time.Time
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.TenantID,
		arg.Email,
		arg.PasswordHash,
		arg.FullName,
		arg.Phone,
		arg.Role,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FullName,
		&i.Phone,
		&i.Role,
		&i.IsActive,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT
    id,
    email,
    full_name,
    phone,
    role,
    is_active,
    last_login_at,
    created_at,
    updated_at
FROM core.users
WHERE id = $1
`

type GetUserRow struct {
	ID          uuid.UUID
	Email       string
	FullName    string
	Phone       *string
	Role        string
	IsActive    bool
	LastLoginAt *time.Time
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

func (q *Queries) GetUser(ctx context.Context, id uuid.UUID) (GetUserRow, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i GetUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FullName,
		&i.Phone,
		&i.Role,
		&i.IsActive,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT
    id,
    email,
    full_name,
    phone,
    role,
    is_active,
    last_login_at,
    created_at,
    updated_at
FROM core.users
WHERE ($1::text IS NULL OR role = $1)
  AND ($2::boolean IS NULL OR is_active = $2)
  AND ($3::uuid IS NULL OR id < $3)
ORDER BY id DESC
LIMIT $4
`

type ListUsersParams struct {
	Role     *string
	IsActive *bool
	After    *uuid.UUID
	RowLimit int32
}

type ListUsersRow struct {
	ID          uuid.UUID
	Email       string
	FullName    string
	Phone       *string
	Role        string
	IsActive    bool
	LastLoginAt *time.Time
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]ListUsersRow, error) {
	rows, err := q.db.Query(ctx, listUsers,
		arg.Role,
		arg.IsActive,
		arg.After,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersRow
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.FullName,
			&i.Phone,
			&i.Role,
			&i.IsActive,
			&i.LastLoginAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockTenant = `-- name: LockTenant :one
SELECT id
FROM core.tenants
WHERE id = $1
FOR UPDATE
`

func (q *Queries) LockTenant(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, lockTenant, id)
	var id_2 uuid.UUID
	err := row.Scan(&id_2)
	return id_2, err
}

const revokeUserSessions = `-- name: RevokeUserSessions :exec
UPDATE core.auth_sessions
SET revoked_at = $1
WHERE user_id = $2
  AND revoked_at IS NULL
`

type RevokeUserSessionsParams struct {
	RevokedAt *time.Time
	UserID    uuid.UUID
}

func (q *Queries) RevokeUserSessions(ctx context.Context, arg RevokeUserSessionsParams) error {
	_, err := q.db.Exec(ctx, revokeUserSessions, arg.RevokedAt, arg.UserID)
	return err
}

const updateUser = `-- name: UpdateUser :one
UPDATE core.users
SET full_name = coalesce($1, full_name),
    phone = CASE WHEN $2::boolean THEN $3 ELSE phone END,
    role = coalesce($4, role),
    is_active = coalesce($5, is_active)
WHERE id = $6
RETURNING
    id,
    email,
    full_name,
    phone,
    role,
    is_active,
    last_login_at,
    created_at,
    updated_at
`

type UpdateUserParams struct {
	FullName *string
	SetPhone bool
	Phone    *string
	Role     *string
	IsActive *bool
	ID       uuid.UUID
}

type UpdateUserRow struct {
	ID          uuid.UUID
	Email       string
	FullName    string
	Phone       *string
	Role        string
	IsActive    bool
	LastLoginAt *time.Time
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (UpdateUserRow, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.FullName,
		arg.SetPhone,
		arg.Phone,
		arg.Role,
		arg.IsActive,
		arg.ID,
	)
	var i UpdateUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FullName,
		&i.Phone,
		&i.Role,
		&i.IsActive,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
