// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: recalls.sql

package queries

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getLot = `-- name: GetLot :one
SELECT
    tenant_id,
    status
FROM core.lots
WHERE id = $1
`

type GetLotRow struct {
	TenantID uuid.UUID
	Status   string
}

func (q *Queries) GetLot(ctx context.Context, id uuid.UUID) (GetLotRow, error) {
	row := q.db.QueryRow(ctx, getLot, id)
	var i GetLotRow
	err := row.Scan(&i.TenantID, &i.Status)
	return i, err
}

const recallLot = `-- name: RecallLot :one
SELECT
    recall_id,
    affected_shipment_count,
    recalled_at
FROM core.recall_lot($1, $2, $3, $4)
`

type RecallLotParams struct {
	LotID       uuid.UUID
	Reason      string
	UserID      uuid.UUID
	Traceparent *string
}

type RecallLotRow struct {
	RecallID              *uuid.UUID
	AffectedShipmentCount *int32
	RecalledAt            *time.Time
}

func (q *Queries) RecallLot(ctx context.Context, arg RecallLotParams) (RecallLotRow, error) {
	row := q.db.QueryRow(ctx, recallLot,
		arg.LotID,
		arg.Reason,
		arg.UserID,
		arg.Traceparent,
	)
	var i RecallLotRow
	err := row.Scan(&i.RecallID, &i.AffectedShipmentCount, &i.RecalledAt)
	return i, err
}
