// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: events.sql

package queries

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getHead = `-- name: GetHead :one
SELECT
    sequence,
    event_hash
FROM core.shipment_events
WHERE shipment_id = $1
ORDER BY sequence DESC
LIMIT 1
`

type GetHeadRow struct {
	Sequence  int32
	EventHash string
}

func (q *Queries) GetHead(ctx context.Context, shipmentID uuid.UUID) (GetHeadRow, error) {
	row := q.db.QueryRow(ctx, getHead, shipmentID)
	var i GetHeadRow
	err := row.Scan(&i.Sequence, &i.EventHash)
	return i, err
}

const insertEvent = `-- name: InsertEvent :exec
INSERT INTO core.shipment_events (
    id,
    shipment_id,
    sequence,
    event_type,
    event_version,
    status,
    actor_tenant_id,
    actor_user_id,
    occurred_at,
    data,
    prev_event_hash,
    event_hash
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12
)
`

type InsertEventParams struct {
	ID            uuid.UUID
	ShipmentID    uuid.UUID
	Sequence      int32
	EventType     string
	EventVersion  int16
	Status        string
	ActorTenantID *uuid.UUID
	ActorUserID   *uuid.UUID
	OccurredAt    time.Time
	Data          []byte
	PrevEventHash string
	EventHash     string
}

func (q *Queries) InsertEvent(ctx context.Context, arg InsertEventParams) error {
	_, err := q.db.Exec(ctx, insertEvent,
		arg.ID,
		arg.ShipmentID,
		arg.Sequence,
		arg.EventType,
		arg.EventVersion,
		arg.Status,
		arg.ActorTenantID,
		arg.ActorUserID,
		arg.OccurredAt,
		arg.Data,
		arg.PrevEventHash,
		arg.EventHash,
	)
	return err
}

const listEvents = `-- name: ListEvents :many
SELECT
    e.id,
    e.shipment_id,
    s.sscc,
    e.sequence,
    e.event_type,
    e.event_version,
    e.status,
    e.actor_tenant_id,
    e.actor_user_id,
    e.occurred_at,
    e.data,
    e.prev_event_hash,
    e.event_hash
FROM core.shipment_events e
JOIN core.shipments s ON s.id = e.shipment_id
WHERE e.shipment_id = $1
  AND e.sequence > $2
ORDER BY e.sequence
LIMIT $3
`

type ListEventsParams struct {
	ShipmentID    uuid.UUID
	AfterSequence int32
	RowLimit      int32
}

type ListEventsRow struct {
	ID            uuid.UUID
	ShipmentID    uuid.UUID
	Sscc          string
	Sequence      int32
	EventType     string
	EventVersion  int16
	Status        string
	ActorTenantID *uuid.UUID
	ActorUserID   *uuid.UUID
	OccurredAt    time.Time
	Data          []byte
	PrevEventHash string
	EventHash     string
}

func (q *Queries) ListEvents(ctx context.Context, arg ListEventsParams) ([]ListEventsRow, error) {
	rows, err := q.db.Query(ctx, listEvents, arg.ShipmentID, arg.AfterSequence, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEventsRow
	for rows.Next() {
		var i ListEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.ShipmentID,
			&i.Sscc,
			&i.Sequence,
			&i.EventType,
			&i.EventVersion,
			&i.Status,
			&i.ActorTenantID,
			&i.ActorUserID,
			&i.OccurredAt,
			&i.Data,
			&i.PrevEventHash,
			&i.EventHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
