// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: handover.sql

package queries

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const consumePickupCode = `-- name: ConsumePickupCode :exec
UPDATE core.pickup_codes
SET consumed_at = $1
WHERE id = $2
`

type ConsumePickupCodeParams struct {
	ConsumedAt *time.Time
	ID         uuid.UUID
}

func (q *Queries) ConsumePickupCode(ctx context.Context, arg ConsumePickupCodeParams) error {
	_, err := q.db.Exec(ctx, consumePickupCode, arg.ConsumedAt, arg.ID)
	return err
}

const insertPickupCode = `-- name: InsertPickupCode :exec
INSERT INTO core.pickup_codes (shipment_id, code_hash, expires_at, issued_by, created_at)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
`

type InsertPickupCodeParams struct {
	ShipmentID uuid.UUID
	CodeHash   []byte
	ExpiresAt  time.Time
	IssuedBy   uuid.UUID
	CreatedAt  time.Time
}

func (q *Queries) InsertPickupCode(ctx context.Context, arg InsertPickupCodeParams) error {
	_, err := q.db.Exec(ctx, insertPickupCode,
		arg.ShipmentID,
		arg.CodeHash,
		arg.ExpiresAt,
		arg.IssuedBy,
		arg.CreatedAt,
	)
	return err
}

const invalidatePickupCodes = `-- name: InvalidatePickupCodes :exec
UPDATE core.pickup_codes
SET invalidated_at = $1
WHERE shipment_id = $2
  AND consumed_at IS NULL
  AND invalidated_at IS NULL
`

type InvalidatePickupCodesParams struct {
	InvalidatedAt *time.Time
	ShipmentID    uuid.UUID
}

func (q *Queries) InvalidatePickupCodes(ctx context.Context, arg InvalidatePickupCodesParams) error {
	_, err := q.db.Exec(ctx, invalidatePickupCodes, arg.InvalidatedAt, arg.ShipmentID)
	return err
}

const lockActivePickupCode = `-- name: LockActivePickupCode :one
SELECT
    id,
    code_hash,
    expires_at,
    failed_attempts
FROM core.pickup_codes
WHERE shipment_id = $1
  AND consumed_at IS NULL
  AND invalidated_at IS NULL
FOR UPDATE
`

type LockActivePickupCodeRow struct {
	ID             uuid.UUID
	CodeHash       []byte
	ExpiresAt      time.Time
	FailedAttempts int16
}

func (q *Queries) LockActivePickupCode(ctx context.Context, shipmentID uuid.UUID) (LockActivePickupCodeRow, error) {
	row := q.db.QueryRow(ctx, lockActivePickupCode, shipmentID)
	var i LockActivePickupCodeRow
	err := row.Scan(
		&i.ID,
		&i.CodeHash,
		&i.ExpiresAt,
		&i.FailedAttempts,
	)
	return i, err
}

const recordFailedAttempt = `-- name: RecordFailedAttempt :one
UPDATE core.pickup_codes
SET failed_attempts = failed_attempts + 1
WHERE id = $1
RETURNING failed_attempts
`

func (q *Queries) RecordFailedAttempt(ctx context.Context, id uuid.UUID) (int16, error) {
	row := q.db.QueryRow(ctx, recordFailedAttempt, id)
	var failed_attempts int16
	err := row.Scan(&failed_attempts)
	return failed_attempts, err
}

const setPickedUp = `-- name: SetPickedUp :exec
UPDATE core.shipments
SET status = 'IN_TRANSIT',
    picked_up_at = $1
WHERE id = $2
`

type SetPickedUpParams struct {
	PickedUpAt *time.Time
	ID         uuid.UUID
}

func (q *Queries) SetPickedUp(ctx context.Context, arg SetPickedUpParams) error {
	_, err := q.db.Exec(ctx, setPickedUp, arg.PickedUpAt, arg.ID)
	return err
}
