// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: shipments.sql

package queries

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/veritrace-platform/core-business-service/internal/calendar"
)

const countShipments = `-- name: CountShipments :one
SELECT
    count(*) FILTER (WHERE s.status = 'CREATED') AS created,
    count(*) FILTER (WHERE s.status = 'IN_TRANSIT') AS in_transit,
    count(*) FILTER (WHERE s.status = 'DELIVERED') AS delivered,
    count(*) FILTER (WHERE s.status = 'CANCELLED') AS cancelled,
    count(*) FILTER (WHERE s.status = 'RECALLED') AS recalled
FROM core.shipments s
WHERE s.id IN (
        SELECT p.shipment_id
        FROM core.shipment_participants p
        WHERE p.tenant_id = (SELECT core.current_tenant_id())
    )
  AND ($1::uuid IS NULL OR s.assigned_driver_id = $1)
`

type CountShipmentsRow struct {
	Created   int64
	InTransit int64
	Delivered int64
	Cancelled int64
	Recalled  int64
}

func (q *Queries) CountShipments(ctx context.Context, driverID *uuid.UUID) (CountShipmentsRow, error) {
	row := q.db.QueryRow(ctx, countShipments, driverID)
	var i CountShipmentsRow
	err := row.Scan(
		&i.Created,
		&i.InTransit,
		&i.Delivered,
		&i.Cancelled,
		&i.Recalled,
	)
	return i, err
}

const deleteParticipant = `-- name: DeleteParticipant :exec
DELETE FROM core.shipment_participants
WHERE shipment_id = $1
  AND tenant_id = $2
  AND role = $3
`

type DeleteParticipantParams struct {
	ShipmentID uuid.UUID
	TenantID   uuid.UUID
	Role       string
}

func (q *Queries) DeleteParticipant(ctx context.Context, arg DeleteParticipantParams) error {
	_, err := q.db.Exec(ctx, deleteParticipant, arg.ShipmentID, arg.TenantID, arg.Role)
	return err
}

const getBalance = `-- name: GetBalance :one
SELECT quantity_on_hand
FROM core.inventory_balances
WHERE location_id = $1
  AND lot_id = $2
`

type GetBalanceParams struct {
	LocationID uuid.UUID
	LotID      uuid.UUID
}

func (q *Queries) GetBalance(ctx context.Context, arg GetBalanceParams) (int32, error) {
	row := q.db.QueryRow(ctx, getBalance, arg.LocationID, arg.LotID)
	var quantity_on_hand int32
	err := row.Scan(&quantity_on_hand)
	return quantity_on_hand, err
}

const getLot = `-- name: GetLot :one
SELECT
    id,
    gtin,
    product_name,
    min_temp_celsius,
    max_temp_celsius,
    lot_number,
    expiration_date,
    status
FROM core.lots
WHERE id = $1
`

type GetLotRow struct {
	ID             uuid.UUID
	Gtin           string
	ProductName    string
	MinTempCelsius float64
	MaxTempCelsius float64
	LotNumber      string
	ExpirationDate calendar.Date
	Status         string
}

func (q *Queries) GetLot(ctx context.Context, id uuid.UUID) (GetLotRow, error) {
	row := q.db.QueryRow(ctx, getLot, id)
	var i GetLotRow
	err := row.Scan(
		&i.ID,
		&i.Gtin,
		&i.ProductName,
		&i.MinTempCelsius,
		&i.MaxTempCelsius,
		&i.LotNumber,
		&i.ExpirationDate,
		&i.Status,
	)
	return i, err
}

const getOwnTenant = `-- name: GetOwnTenant :one
SELECT
    id,
    code,
    legal_name
FROM core.tenants
WHERE id = $1
`

type GetOwnTenantRow struct {
	ID        uuid.UUID
	Code      string
	LegalName string
}

func (q *Queries) GetOwnTenant(ctx context.Context, id uuid.UUID) (GetOwnTenantRow, error) {
	row := q.db.QueryRow(ctx, getOwnTenant, id)
	var i GetOwnTenantRow
	err := row.Scan(&i.ID, &i.Code, &i.LegalName)
	return i, err
}

const getShipment = `-- name: GetShipment :one
SELECT
    id,
    owner_tenant_id,
    sscc,
    lot_id,
    quantity,
    gtin,
    product_name,
    lot_number,
    expiration_date,
    min_temp_celsius,
    max_temp_celsius,
    origin_location_id,
    origin_gln,
    origin_name,
    origin_latitude,
    origin_longitude,
    origin_geo_fence_radius_meters,
    destination_location_id,
    destination_gln,
    destination_name,
    destination_latitude,
    destination_longitude,
    destination_geo_fence_radius_meters,
    consignee_tenant_id,
    carrier_tenant_id,
    assigned_driver_id,
    status,
    picked_up_at,
    delivered_at,
    cancelled_at,
    recalled_at,
    created_at,
    updated_at
FROM core.shipments
WHERE id = $1
`

type GetShipmentRow struct {
	ID                              uuid.UUID
	OwnerTenantID                   uuid.UUID
	Sscc                            string
	LotID                           uuid.UUID
	Quantity                        int32
	Gtin                            string
	ProductName                     string
	LotNumber                       string
	ExpirationDate                  calendar.Date
	MinTempCelsius                  float64
	MaxTempCelsius                  float64
	OriginLocationID                uuid.UUID
	OriginGln                       string
	OriginName                      string
	OriginLatitude                  float64
	OriginLongitude                 float64
	OriginGeoFenceRadiusMeters      int32
	DestinationLocationID           uuid.UUID
	DestinationGln                  string
	DestinationName                 string
	DestinationLatitude             float64
	DestinationLongitude            float64
	DestinationGeoFenceRadiusMeters int32
	ConsigneeTenantID               uuid.UUID
	CarrierTenantID                 uuid.UUID
	AssignedDriverID                *uuid.UUID
	Status                          string
	PickedUpAt                      *time.Time
	DeliveredAt                     *time.Time
	CancelledAt                     *time.Time
	RecalledAt                      *time.Time
	CreatedAt                       time.Time
	UpdatedAt                       time.Time
}

func (q *Queries) GetShipment(ctx context.Context, id uuid.UUID) (GetShipmentRow, error) {
	row := q.db.QueryRow(ctx, getShipment, id)
	var i GetShipmentRow
	err := row.Scan(
		&i.ID,
		&i.OwnerTenantID,
		&i.Sscc,
		&i.LotID,
		&i.Quantity,
		&i.Gtin,
		&i.ProductName,
		&i.LotNumber,
		&i.ExpirationDate,
		&i.MinTempCelsius,
		&i.MaxTempCelsius,
		&i.OriginLocationID,
		&i.OriginGln,
		&i.OriginName,
		&i.OriginLatitude,
		&i.OriginLongitude,
		&i.OriginGeoFenceRadiusMeters,
		&i.DestinationLocationID,
		&i.DestinationGln,
		&i.DestinationName,
		&i.DestinationLatitude,
		&i.DestinationLongitude,
		&i.DestinationGeoFenceRadiusMeters,
		&i.ConsigneeTenantID,
		&i.CarrierTenantID,
		&i.AssignedDriverID,
		&i.Status,
		&i.PickedUpAt,
		&i.DeliveredAt,
		&i.CancelledAt,
		&i.RecalledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT
    role,
    is_active
FROM core.users
WHERE id = $1
`

type GetUserRow struct {
	Role     string
	IsActive bool
}

func (q *Queries) GetUser(ctx context.Context, id uuid.UUID) (GetUserRow, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i GetUserRow
	err := row.Scan(&i.Role, &i.IsActive)
	return i, err
}

const insertParticipant = `-- name: InsertParticipant :exec
INSERT INTO core.shipment_participants (shipment_id, tenant_id, role, tenant_code, tenant_legal_name, created_at)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
`

type InsertParticipantParams struct {
	ShipmentID      uuid.UUID
	TenantID        uuid.UUID
	Role            string
	TenantCode      string
	TenantLegalName string
	CreatedAt       time.Time
}

func (q *Queries) InsertParticipant(ctx context.Context, arg InsertParticipantParams) error {
	_, err := q.db.Exec(ctx, insertParticipant,
		arg.ShipmentID,
		arg.TenantID,
		arg.Role,
		arg.TenantCode,
		arg.TenantLegalName,
		arg.CreatedAt,
	)
	return err
}

const insertShipment = `-- name: InsertShipment :one
INSERT INTO core.shipments (
    owner_tenant_id,
    sscc,
    lot_id,
    quantity,
    gtin,
    product_name,
    lot_number,
    expiration_date,
    min_temp_celsius,
    max_temp_celsius,
    origin_location_id,
    origin_gln,
    origin_name,
    origin_latitude,
    origin_longitude,
    origin_geo_fence_radius_meters,
    destination_location_id,
    destination_gln,
    destination_name,
    destination_latitude,
    destination_longitude,
    destination_geo_fence_radius_meters,
    consignee_tenant_id,
    carrier_tenant_id,
    assigned_driver_id,
    created_by,
    created_at,
    updated_at
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13,
    $14,
    $15,
    $16,
    $17,
    $18,
    $19,
    $20,
    $21,
    $22,
    $23,
    $24,
    $25,
    $26,
    $27,
    $27
)
RETURNING id
`

type InsertShipmentParams struct {
	OwnerTenantID                   uuid.UUID
	Sscc                            string
	LotID                           uuid.UUID
	Quantity                        int32
	Gtin                            string
	ProductName                     string
	LotNumber                       string
	ExpirationDate                  calendar.Date
	MinTempCelsius                  float64
	MaxTempCelsius                  float64
	OriginLocationID                uuid.UUID
	OriginGln                       string
	OriginName                      string
	OriginLatitude                  float64
	OriginLongitude                 float64
	OriginGeoFenceRadiusMeters      int32
	DestinationLocationID           uuid.UUID
	DestinationGln                  string
	DestinationName                 string
	DestinationLatitude             float64
	DestinationLongitude            float64
	DestinationGeoFenceRadiusMeters int32
	ConsigneeTenantID               uuid.UUID
	CarrierTenantID                 uuid.UUID
	AssignedDriverID                *uuid.UUID
	CreatedBy                       uuid.UUID
	CreatedAt                       time.Time
}

func (q *Queries) InsertShipment(ctx context.Context, arg InsertShipmentParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertShipment,
		arg.OwnerTenantID,
		arg.Sscc,
		arg.LotID,
		arg.Quantity,
		arg.Gtin,
		arg.ProductName,
		arg.LotNumber,
		arg.ExpirationDate,
		arg.MinTempCelsius,
		arg.MaxTempCelsius,
		arg.OriginLocationID,
		arg.OriginGln,
		arg.OriginName,
		arg.OriginLatitude,
		arg.OriginLongitude,
		arg.OriginGeoFenceRadiusMeters,
		arg.DestinationLocationID,
		arg.DestinationGln,
		arg.DestinationName,
		arg.DestinationLatitude,
		arg.DestinationLongitude,
		arg.DestinationGeoFenceRadiusMeters,
		arg.ConsigneeTenantID,
		arg.CarrierTenantID,
		arg.AssignedDriverID,
		arg.CreatedBy,
		arg.CreatedAt,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const listParticipants = `-- name: ListParticipants :many
SELECT
    shipment_id,
    tenant_id,
    role,
    tenant_code,
    tenant_legal_name
FROM core.shipment_participants
WHERE shipment_id = ANY ($1::uuid[])
ORDER BY shipment_id, created_at, role
`

type ListParticipantsRow struct {
	ShipmentID      uuid.UUID
	TenantID        uuid.UUID
	Role            string
	TenantCode      string
	TenantLegalName string
}

func (q *Queries) ListParticipants(ctx context.Context, shipmentIds []uuid.UUID) ([]ListParticipantsRow, error) {
	rows, err := q.db.Query(ctx, listParticipants, shipmentIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListParticipantsRow
	for rows.Next() {
		var i ListParticipantsRow
		if err := rows.Scan(
			&i.ShipmentID,
			&i.TenantID,
			&i.Role,
			&i.TenantCode,
			&i.TenantLegalName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listShipments = `-- name: ListShipments :many
SELECT
    s.id,
    s.owner_tenant_id,
    s.sscc,
    s.lot_id,
    s.quantity,
    s.gtin,
    s.product_name,
    s.lot_number,
    s.expiration_date,
    s.min_temp_celsius,
    s.max_temp_celsius,
    s.origin_location_id,
    s.origin_gln,
    s.origin_name,
    s.origin_latitude,
    s.origin_longitude,
    s.origin_geo_fence_radius_meters,
    s.destination_location_id,
    s.destination_gln,
    s.destination_name,
    s.destination_latitude,
    s.destination_longitude,
    s.destination_geo_fence_radius_meters,
    s.consignee_tenant_id,
    s.carrier_tenant_id,
    s.assigned_driver_id,
    s.status,
    s.picked_up_at,
    s.delivered_at,
    s.cancelled_at,
    s.recalled_at,
    s.created_at,
    s.updated_at
FROM core.shipments s
WHERE s.id IN (
        SELECT p.shipment_id
        FROM core.shipment_participants p
        WHERE p.tenant_id = (SELECT core.current_tenant_id())
          AND ($1::text IS NULL OR p.role = $1)
    )
  AND ($2::text IS NULL OR s.status = $2)
  AND ($3::text IS NULL OR s.sscc = $3)
  AND ($4::uuid IS NULL OR s.lot_id = $4)
  AND ($5::uuid IS NULL OR s.assigned_driver_id = $5)
  AND ($6::uuid IS NULL OR s.id < $6)
ORDER BY s.id DESC
LIMIT $7
`

type ListShipmentsParams struct {
	Party    *string
	Status   *string
	Sscc     *string
	LotID    *uuid.UUID
	DriverID *uuid.UUID
	After    *uuid.UUID
	RowLimit int32
}

type ListShipmentsRow struct {
	ID                              uuid.UUID
	OwnerTenantID                   uuid.UUID
	Sscc                            string
	LotID                           uuid.UUID
	Quantity                        int32
	Gtin                            string
	ProductName                     string
	LotNumber                       string
	ExpirationDate                  calendar.Date
	MinTempCelsius                  float64
	MaxTempCelsius                  float64
	OriginLocationID                uuid.UUID
	OriginGln                       string
	OriginName                      string
	OriginLatitude                  float64
	OriginLongitude                 float64
	OriginGeoFenceRadiusMeters      int32
	DestinationLocationID           uuid.UUID
	DestinationGln                  string
	DestinationName                 string
	DestinationLatitude             float64
	DestinationLongitude            float64
	DestinationGeoFenceRadiusMeters int32
	ConsigneeTenantID               uuid.UUID
	CarrierTenantID                 uuid.UUID
	AssignedDriverID                *uuid.UUID
	Status                          string
	PickedUpAt                      *time.Time
	DeliveredAt                     *time.Time
	CancelledAt                     *time.Time
	RecalledAt                      *time.Time
	CreatedAt                       time.Time
	UpdatedAt                       time.Time
}

func (q *Queries) ListShipments(ctx context.Context, arg ListShipmentsParams) ([]ListShipmentsRow, error) {
	rows, err := q.db.Query(ctx, listShipments,
		arg.Party,
		arg.Status,
		arg.Sscc,
		arg.LotID,
		arg.DriverID,
		arg.After,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListShipmentsRow
	for rows.Next() {
		var i ListShipmentsRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerTenantID,
			&i.Sscc,
			&i.LotID,
			&i.Quantity,
			&i.Gtin,
			&i.ProductName,
			&i.LotNumber,
			&i.ExpirationDate,
			&i.MinTempCelsius,
			&i.MaxTempCelsius,
			&i.OriginLocationID,
			&i.OriginGln,
			&i.OriginName,
			&i.OriginLatitude,
			&i.OriginLongitude,
			&i.OriginGeoFenceRadiusMeters,
			&i.DestinationLocationID,
			&i.DestinationGln,
			&i.DestinationName,
			&i.DestinationLatitude,
			&i.DestinationLongitude,
			&i.DestinationGeoFenceRadiusMeters,
			&i.ConsigneeTenantID,
			&i.CarrierTenantID,
			&i.AssignedDriverID,
			&i.Status,
			&i.PickedUpAt,
			&i.DeliveredAt,
			&i.CancelledAt,
			&i.RecalledAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockLocation = `-- name: LockLocation :one
SELECT
    id,
    gln,
    name,
    latitude,
    longitude,
    geo_fence_radius_meters,
    is_active
FROM core.locations
WHERE id = $1
FOR SHARE
`

type LockLocationRow struct {
	ID                   uuid.UUID
	Gln                  string
	Name                 string
	Latitude             float64
	Longitude            float64
	GeoFenceRadiusMeters int32
	IsActive             bool
}

func (q *Queries) LockLocation(ctx context.Context, id uuid.UUID) (LockLocationRow, error) {
	row := q.db.QueryRow(ctx, lockLocation, id)
	var i LockLocationRow
	err := row.Scan(
		&i.ID,
		&i.Gln,
		&i.Name,
		&i.Latitude,
		&i.Longitude,
		&i.GeoFenceRadiusMeters,
		&i.IsActive,
	)
	return i, err
}

const lockLotForShipment = `-- name: LockLotForShipment :exec
SELECT pg_advisory_xact_lock_shared(47154002, hashtext($1::uuid::text))
`

// Shipment creation takes the lot's lock in shared mode and a recall takes it exclusively, so a recall waits for
// shipments being created from the lot, and blocks new ones until it commits.
func (q *Queries) LockLotForShipment(ctx context.Context, lotID uuid.UUID) error {
	_, err := q.db.Exec(ctx, lockLotForShipment, lotID)
	return err
}

const lockShipment = `-- name: LockShipment :one
SELECT
    id,
    owner_tenant_id,
    sscc,
    lot_id,
    quantity,
    gtin,
    product_name,
    lot_number,
    expiration_date,
    min_temp_celsius,
    max_temp_celsius,
    origin_location_id,
    origin_gln,
    origin_name,
    origin_latitude,
    origin_longitude,
    origin_geo_fence_radius_meters,
    destination_location_id,
    destination_gln,
    destination_name,
    destination_latitude,
    destination_longitude,
    destination_geo_fence_radius_meters,
    consignee_tenant_id,
    carrier_tenant_id,
    assigned_driver_id,
    status,
    picked_up_at,
    delivered_at,
    cancelled_at,
    recalled_at,
    created_at,
    updated_at
FROM core.shipments
WHERE id = $1
FOR UPDATE
`

type LockShipmentRow struct {
	ID                              uuid.UUID
	OwnerTenantID                   uuid.UUID
	Sscc                            string
	LotID                           uuid.UUID
	Quantity                        int32
	Gtin                            string
	ProductName                     string
	LotNumber                       string
	ExpirationDate                  calendar.Date
	MinTempCelsius                  float64
	MaxTempCelsius                  float64
	OriginLocationID                uuid.UUID
	OriginGln                       string
	OriginName                      string
	OriginLatitude                  float64
	OriginLongitude                 float64
	OriginGeoFenceRadiusMeters      int32
	DestinationLocationID           uuid.UUID
	DestinationGln                  string
	DestinationName                 string
	DestinationLatitude             float64
	DestinationLongitude            float64
	DestinationGeoFenceRadiusMeters int32
	ConsigneeTenantID               uuid.UUID
	CarrierTenantID                 uuid.UUID
	AssignedDriverID                *uuid.UUID
	Status                          string
	PickedUpAt                      *time.Time
	DeliveredAt                     *time.Time
	CancelledAt                     *time.Time
	RecalledAt                      *time.Time
	CreatedAt                       time.Time
	UpdatedAt                       time.Time
}

func (q *Queries) LockShipment(ctx context.Context, id uuid.UUID) (LockShipmentRow, error) {
	row := q.db.QueryRow(ctx, lockShipment, id)
	var i LockShipmentRow
	err := row.Scan(
		&i.ID,
		&i.OwnerTenantID,
		&i.Sscc,
		&i.LotID,
		&i.Quantity,
		&i.Gtin,
		&i.ProductName,
		&i.LotNumber,
		&i.ExpirationDate,
		&i.MinTempCelsius,
		&i.MaxTempCelsius,
		&i.OriginLocationID,
		&i.OriginGln,
		&i.OriginName,
		&i.OriginLatitude,
		&i.OriginLongitude,
		&i.OriginGeoFenceRadiusMeters,
		&i.DestinationLocationID,
		&i.DestinationGln,
		&i.DestinationName,
		&i.DestinationLatitude,
		&i.DestinationLongitude,
		&i.DestinationGeoFenceRadiusMeters,
		&i.ConsigneeTenantID,
		&i.CarrierTenantID,
		&i.AssignedDriverID,
		&i.Status,
		&i.PickedUpAt,
		&i.DeliveredAt,
		&i.CancelledAt,
		&i.RecalledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const lookupLocation = `-- name: LookupLocation :one
SELECT
    location_id,
    gln,
    name,
    latitude,
    longitude,
    geo_fence_radius_meters,
    tenant_id,
    tenant_code,
    tenant_legal_name
FROM core.lookup_location_by_gln($1)
`

type LookupLocationRow struct {
	LocationID           *uuid.UUID
	Gln                  *string
	Name                 *string
	Latitude             *float64
	Longitude            *float64
	GeoFenceRadiusMeters *int32
	TenantID             *uuid.UUID
	TenantCode           *string
	TenantLegalName      *string
}

func (q *Queries) LookupLocation(ctx context.Context, gln string) (LookupLocationRow, error) {
	row := q.db.QueryRow(ctx, lookupLocation, gln)
	var i LookupLocationRow
	err := row.Scan(
		&i.LocationID,
		&i.Gln,
		&i.Name,
		&i.Latitude,
		&i.Longitude,
		&i.GeoFenceRadiusMeters,
		&i.TenantID,
		&i.TenantCode,
		&i.TenantLegalName,
	)
	return i, err
}

const lookupTenant = `-- name: LookupTenant :one
SELECT
    tenant_id,
    code,
    legal_name
FROM core.lookup_tenant_by_code($1)
`

type LookupTenantRow struct {
	TenantID  *uuid.UUID
	Code      *string
	LegalName *string
}

func (q *Queries) LookupTenant(ctx context.Context, code string) (LookupTenantRow, error) {
	row := q.db.QueryRow(ctx, lookupTenant, code)
	var i LookupTenantRow
	err := row.Scan(&i.TenantID, &i.Code, &i.LegalName)
	return i, err
}

const setCancelled = `-- name: SetCancelled :exec
UPDATE core.shipments
SET status = 'CANCELLED',
    cancelled_at = $1
WHERE id = $2
`

type SetCancelledParams struct {
	CancelledAt *time.Time
	ID          uuid.UUID
}

func (q *Queries) SetCancelled(ctx context.Context, arg SetCancelledParams) error {
	_, err := q.db.Exec(ctx, setCancelled, arg.CancelledAt, arg.ID)
	return err
}

const setCarrier = `-- name: SetCarrier :exec
UPDATE core.shipments
SET carrier_tenant_id = $1,
    assigned_driver_id = NULL
WHERE id = $2
`

type SetCarrierParams struct {
	CarrierTenantID uuid.UUID
	ID              uuid.UUID
}

func (q *Queries) SetCarrier(ctx context.Context, arg SetCarrierParams) error {
	_, err := q.db.Exec(ctx, setCarrier, arg.CarrierTenantID, arg.ID)
	return err
}

const setDriver = `-- name: SetDriver :exec
UPDATE core.shipments
SET assigned_driver_id = $1
WHERE id = $2
`

type SetDriverParams struct {
	AssignedDriverID *uuid.UUID
	ID               uuid.UUID
}

func (q *Queries) SetDriver(ctx context.Context, arg SetDriverParams) error {
	_, err := q.db.Exec(ctx, setDriver, arg.AssignedDriverID, arg.ID)
	return err
}

const takeSSCCSerial = `-- name: TakeSSCCSerial :one
UPDATE core.tenants
SET sscc_next_serial = sscc_next_serial + 1
WHERE id = $1
RETURNING
    (sscc_next_serial - 1)::bigint AS serial,
    sscc_extension_digit,
    gs1_company_prefix
`

type TakeSSCCSerialRow struct {
	Serial             int64
	SsccExtensionDigit int16
	Gs1CompanyPrefix   string
}

func (q *Queries) TakeSSCCSerial(ctx context.Context, id uuid.UUID) (TakeSSCCSerialRow, error) {
	row := q.db.QueryRow(ctx, takeSSCCSerial, id)
	var i TakeSSCCSerialRow
	err := row.Scan(&i.Serial, &i.SsccExtensionDigit, &i.Gs1CompanyPrefix)
	return i, err
}
