// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: lots.sql

package queries

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/veritrace-platform/core-business-service/internal/calendar"
)

const createLot = `-- name: CreateLot :one
INSERT INTO core.lots (
    tenant_id,
    product_id,
    gtin,
    product_name,
    min_temp_celsius,
    max_temp_celsius,
    lot_number,
    production_date,
    expiration_date,
    quantity_commissioned,
    commissioned_location_id,
    created_by
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12
)
RETURNING
    id,
    tenant_id,
    product_id,
    gtin,
    product_name,
    min_temp_celsius,
    max_temp_celsius,
    lot_number,
    production_date,
    expiration_date,
    quantity_commissioned,
    commissioned_location_id,
    status,
    recalled_at,
    created_at,
    updated_at
`

type CreateLotParams struct {
	TenantID               uuid.UUID
	ProductID              uuid.UUID
	Gtin                   string
	ProductName            string
	MinTempCelsius         float64
	MaxTempCelsius         float64
	LotNumber              string
	ProductionDate         calendar.Date
	ExpirationDate         calendar.Date
	QuantityCommissioned   int32
	CommissionedLocationID uuid.UUID
	CreatedBy              uuid.UUID
}

type CreateLotRow struct {
	ID                     uuid.UUID
	TenantID               uuid.UUID
	ProductID              uuid.UUID
	Gtin                   string
	ProductName            string
	MinTempCelsius         float64
	MaxTempCelsius         float64
	LotNumber              string
	ProductionDate         calendar.Date
	ExpirationDate         calendar.Date
	QuantityCommissioned   int32
	CommissionedLocationID uuid.UUID
	Status                 string
	RecalledAt             *time.Time
	CreatedAt              time.Time
	UpdatedAt              time.Time
}

func (q *Queries) CreateLot(ctx context.Context, arg CreateLotParams) (CreateLotRow, error) {
	row := q.db.QueryRow(ctx, createLot,
		arg.TenantID,
		arg.ProductID,
		arg.Gtin,
		arg.ProductName,
		arg.MinTempCelsius,
		arg.MaxTempCelsius,
		arg.LotNumber,
		arg.ProductionDate,
		arg.ExpirationDate,
		arg.QuantityCommissioned,
		arg.CommissionedLocationID,
		arg.CreatedBy,
	)
	var i CreateLotRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ProductID,
		&i.Gtin,
		&i.ProductName,
		&i.MinTempCelsius,
		&i.MaxTempCelsius,
		&i.LotNumber,
		&i.ProductionDate,
		&i.ExpirationDate,
		&i.QuantityCommissioned,
		&i.CommissionedLocationID,
		&i.Status,
		&i.RecalledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLot = `-- name: GetLot :one
SELECT
    id,
    tenant_id,
    product_id,
    gtin,
    product_name,
    min_temp_celsius,
    max_temp_celsius,
    lot_number,
    production_date,
    expiration_date,
    quantity_commissioned,
    commissioned_location_id,
    status,
    recalled_at,
    created_at,
    updated_at
FROM core.lots
WHERE id = $1
`

type GetLotRow struct {
	ID                     uuid.UUID
	TenantID               uuid.UUID
	ProductID              uuid.UUID
	Gtin                   string
	ProductName            string
	MinTempCelsius         float64
	MaxTempCelsius         float64
	LotNumber              string
	ProductionDate         calendar.Date
	ExpirationDate         calendar.Date
	QuantityCommissioned   int32
	CommissionedLocationID uuid.UUID
	Status                 string
	RecalledAt             *time.Time
	CreatedAt              time.Time
	UpdatedAt              time.Time
}

func (q *Queries) GetLot(ctx context.Context, id uuid.UUID) (GetLotRow, error) {
	row := q.db.QueryRow(ctx, getLot, id)
	var i GetLotRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ProductID,
		&i.Gtin,
		&i.ProductName,
		&i.MinTempCelsius,
		&i.MaxTempCelsius,
		&i.LotNumber,
		&i.ProductionDate,
		&i.ExpirationDate,
		&i.QuantityCommissioned,
		&i.CommissionedLocationID,
		&i.Status,
		&i.RecalledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listLots = `-- name: ListLots :many
SELECT
    id,
    tenant_id,
    product_id,
    gtin,
    product_name,
    min_temp_celsius,
    max_temp_celsius,
    lot_number,
    production_date,
    expiration_date,
    quantity_commissioned,
    commissioned_location_id,
    status,
    recalled_at,
    created_at,
    updated_at
FROM core.lots
WHERE ($1::uuid IS NULL OR product_id = $1)
  AND ($2::text IS NULL OR status = $2)
  AND ($3::uuid IS NULL OR id < $3)
ORDER BY id DESC
LIMIT $4
`

type ListLotsParams struct {
	ProductID *uuid.UUID
	Status    *string
	After     *uuid.UUID
	RowLimit  int32
}

type ListLotsRow struct {
	ID                     uuid.UUID
	TenantID               uuid.UUID
	ProductID              uuid.UUID
	Gtin                   string
	ProductName            string
	MinTempCelsius         float64
	MaxTempCelsius         float64
	LotNumber              string
	ProductionDate         calendar.Date
	ExpirationDate         calendar.Date
	QuantityCommissioned   int32
	CommissionedLocationID uuid.UUID
	Status                 string
	RecalledAt             *time.Time
	CreatedAt              time.Time
	UpdatedAt              time.Time
}

func (q *Queries) ListLots(ctx context.Context, arg ListLotsParams) ([]ListLotsRow, error) {
	rows, err := q.db.Query(ctx, listLots,
		arg.ProductID,
		arg.Status,
		arg.After,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLotsRow
	for rows.Next() {
		var i ListLotsRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ProductID,
			&i.Gtin,
			&i.ProductName,
			&i.MinTempCelsius,
			&i.MaxTempCelsius,
			&i.LotNumber,
			&i.ProductionDate,
			&i.ExpirationDate,
			&i.QuantityCommissioned,
			&i.CommissionedLocationID,
			&i.Status,
			&i.RecalledAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockLocation = `-- name: LockLocation :one
SELECT
    id,
    is_active
FROM core.locations
WHERE id = $1
FOR SHARE
`

type LockLocationRow struct {
	ID       uuid.UUID
	IsActive bool
}

// Commissioning locks the location until it commits, so the location is not deactivated meanwhile.
func (q *Queries) LockLocation(ctx context.Context, id uuid.UUID) (LockLocationRow, error) {
	row := q.db.QueryRow(ctx, lockLocation, id)
	var i LockLocationRow
	err := row.Scan(&i.ID, &i.IsActive)
	return i, err
}

const lockProduct = `-- name: LockProduct :one
SELECT
    id,
    gtin,
    name,
    min_temp_celsius,
    max_temp_celsius,
    is_active
FROM core.products
WHERE id = $1
FOR SHARE
`

type LockProductRow struct {
	ID             uuid.UUID
	Gtin           string
	Name           string
	MinTempCelsius float64
	MaxTempCelsius float64
	IsActive       bool
}

// Commissioning locks the product until it commits, so the product is neither changed nor deactivated between
// the checks and the new lot.
func (q *Queries) LockProduct(ctx context.Context, id uuid.UUID) (LockProductRow, error) {
	row := q.db.QueryRow(ctx, lockProduct, id)
	var i LockProductRow
	err := row.Scan(
		&i.ID,
		&i.Gtin,
		&i.Name,
		&i.MinTempCelsius,
		&i.MaxTempCelsius,
		&i.IsActive,
	)
	return i, err
}
