// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: products.sql

package queries

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createProduct = `-- name: CreateProduct :one
INSERT INTO core.products (
    tenant_id,
    gtin,
    name,
    description,
    min_temp_celsius,
    max_temp_celsius
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
RETURNING
    id,
    gtin,
    name,
    description,
    min_temp_celsius,
    max_temp_celsius,
    is_active,
    created_at,
    updated_at
`

type CreateProductParams struct {
	TenantID       uuid.UUID
	Gtin           string
	Name           string
	Description    *string
	MinTempCelsius float64
	MaxTempCelsius float64
}

type CreateProductRow struct {
	ID             uuid.UUID
	Gtin           string
	Name           string
	Description    *string
	MinTempCelsius float64
	MaxTempCelsius float64
	IsActive       bool
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (CreateProductRow, error) {
	row := q.db.QueryRow(ctx, createProduct,
		arg.TenantID,
		arg.Gtin,
		arg.Name,
		arg.Description,
		arg.MinTempCelsius,
		arg.MaxTempCelsius,
	)
	var i CreateProductRow
	err := row.Scan(
		&i.ID,
		&i.Gtin,
		&i.Name,
		&i.Description,
		&i.MinTempCelsius,
		&i.MaxTempCelsius,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCompanyPrefix = `-- name: GetCompanyPrefix :one
SELECT gs1_company_prefix
FROM core.tenants
WHERE id = $1
`

func (q *Queries) GetCompanyPrefix(ctx context.Context, id uuid.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getCompanyPrefix, id)
	var gs1_company_prefix string
	err := row.Scan(&gs1_company_prefix)
	return gs1_company_prefix, err
}

const getProduct = `-- name: GetProduct :one
SELECT
    id,
    gtin,
    name,
    description,
    min_temp_celsius,
    max_temp_celsius,
    is_active,
    created_at,
    updated_at
FROM core.products
WHERE id = $1
`

type GetProductRow struct {
	ID             uuid.UUID
	Gtin           string
	Name           string
	Description    *string
	MinTempCelsius float64
	MaxTempCelsius float64
	IsActive       bool
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

func (q *Queries) GetProduct(ctx context.Context, id uuid.UUID) (GetProductRow, error) {
	row := q.db.QueryRow(ctx, getProduct, id)
	var i GetProductRow
	err := row.Scan(
		&i.ID,
		&i.Gtin,
		&i.Name,
		&i.Description,
		&i.MinTempCelsius,
		&i.MaxTempCelsius,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProducts = `-- name: ListProducts :many
SELECT
    id,
    gtin,
    name,
    description,
    min_temp_celsius,
    max_temp_celsius,
    is_active,
    created_at,
    updated_at
FROM core.products
WHERE ($1::boolean IS NULL OR is_active = $1)
  AND ($2::text IS NULL OR name ILIKE $2 OR gtin LIKE $2)
  AND ($3::uuid IS NULL OR id < $3)
ORDER BY id DESC
LIMIT $4
`

type ListProductsParams struct {
	IsActive *bool
	Pattern  *string
	After    *uuid.UUID
	RowLimit int32
}

type ListProductsRow struct {
	ID             uuid.UUID
	Gtin           string
	Name           string
	Description    *string
	MinTempCelsius float64
	MaxTempCelsius float64
	IsActive       bool
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

func (q *Queries) ListProducts(ctx context.Context, arg ListProductsParams) ([]ListProductsRow, error) {
	rows, err := q.db.Query(ctx, listProducts,
		arg.IsActive,
		arg.Pattern,
		arg.After,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProductsRow
	for rows.Next() {
		var i ListProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.Gtin,
			&i.Name,
			&i.Description,
			&i.MinTempCelsius,
			&i.MaxTempCelsius,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProduct = `-- name: UpdateProduct :one
UPDATE core.products
SET name = coalesce($1, name),
    description = CASE WHEN $2::boolean THEN $3 ELSE description END,
    min_temp_celsius = coalesce($4, min_temp_celsius),
    max_temp_celsius = coalesce($5, max_temp_celsius),
    is_active = coalesce($6, is_active)
WHERE id = $7
RETURNING
    id,
    gtin,
    name,
    description,
    min_temp_celsius,
    max_temp_celsius,
    is_active,
    created_at,
    updated_at
`

type UpdateProductParams struct {
	Name           *string
	SetDescription bool
	Description    *string
	MinTempCelsius *float64
	MaxTempCelsius *float64
	IsActive       *bool
	ID             uuid.UUID
}

type UpdateProductRow struct {
	ID             uuid.UUID
	Gtin           string
	Name           string
	Description    *string
	MinTempCelsius float64
	MaxTempCelsius float64
	IsActive       bool
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) (UpdateProductRow, error) {
	row := q.db.QueryRow(ctx, updateProduct,
		arg.Name,
		arg.SetDescription,
		arg.Description,
		arg.MinTempCelsius,
		arg.MaxTempCelsius,
		arg.IsActive,
		arg.ID,
	)
	var i UpdateProductRow
	err := row.Scan(
		&i.ID,
		&i.Gtin,
		&i.Name,
		&i.Description,
		&i.MinTempCelsius,
		&i.MaxTempCelsius,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
