// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package queries

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createSession = `-- name: CreateSession :one
INSERT INTO core.auth_sessions (
    tenant_id,
    user_id,
    family_id,
    token_hash,
    expires_at,
    user_agent
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
RETURNING id
`

type CreateSessionParams struct {
	TenantID  uuid.UUID
	UserID    uuid.UUID
	FamilyID  uuid.UUID
	TokenHash []byte
	ExpiresAt time.Time
	UserAgent *string
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.TenantID,
		arg.UserID,
		arg.FamilyID,
		arg.TokenHash,
		arg.ExpiresAt,
		arg.UserAgent,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const deleteExpiredFamilySessions = `-- name: DeleteExpiredFamilySessions :exec
DELETE FROM core.auth_sessions
WHERE family_id = $1
  AND expires_at < $2
`

type DeleteExpiredFamilySessionsParams struct {
	FamilyID uuid.UUID
	Before   time.Time
}

func (q *Queries) DeleteExpiredFamilySessions(ctx context.Context, arg DeleteExpiredFamilySessionsParams) error {
	_, err := q.db.Exec(ctx, deleteExpiredFamilySessions, arg.FamilyID, arg.Before)
	return err
}

const deleteExpiredUserSessions = `-- name: DeleteExpiredUserSessions :exec
DELETE FROM core.auth_sessions
WHERE user_id = $1
  AND expires_at < $2
`

type DeleteExpiredUserSessionsParams struct {
	UserID uuid.UUID
	Before time.Time
}

func (q *Queries) DeleteExpiredUserSessions(ctx context.Context, arg DeleteExpiredUserSessionsParams) error {
	_, err := q.db.Exec(ctx, deleteExpiredUserSessions, arg.UserID, arg.Before)
	return err
}

const findAuthSession = `-- name: FindAuthSession :one
SELECT
    session_id,
    family_id,
    tenant_id,
    user_id
FROM core.find_auth_session($1)
`

type FindAuthSessionRow struct {
	SessionID *uuid.UUID
	FamilyID  *uuid.UUID
	TenantID  *uuid.UUID
	UserID    *uuid.UUID
}

func (q *Queries) FindAuthSession(ctx context.Context, tokenHash []byte) (FindAuthSessionRow, error) {
	row := q.db.QueryRow(ctx, findAuthSession, tokenHash)
	var i FindAuthSessionRow
	err := row.Scan(
		&i.SessionID,
		&i.FamilyID,
		&i.TenantID,
		&i.UserID,
	)
	return i, err
}

const findLoginUser = `-- name: FindLoginUser :one
SELECT
    user_id,
    tenant_id,
    password_hash,
    role,
    is_active
FROM core.find_login_user($1)
`

type FindLoginUserRow struct {
	UserID       *uuid.UUID
	TenantID     *uuid.UUID
	PasswordHash *string
	Role         *string
	IsActive     *bool
}

func (q *Queries) FindLoginUser(ctx context.Context, email string) (FindLoginUserRow, error) {
	row := q.db.QueryRow(ctx, findLoginUser, email)
	var i FindLoginUserRow
	err := row.Scan(
		&i.UserID,
		&i.TenantID,
		&i.PasswordHash,
		&i.Role,
		&i.IsActive,
	)
	return i, err
}

const getMe = `-- name: GetMe :one
SELECT
    u.id,
    u.email,
    u.full_name,
    u.phone,
    u.role,
    u.is_active,
    u.last_login_at,
    u.created_at,
    u.updated_at,
    t.id AS tenant_id,
    t.code AS tenant_code,
    t.legal_name AS tenant_legal_name,
    t.gs1_company_prefix AS tenant_gs1_company_prefix,
    t.status AS tenant_status
FROM core.users u
JOIN core.tenants t ON t.id = u.tenant_id
WHERE u.id = $1
`

type GetMeRow struct {
	ID                     uuid.UUID
	Email                  string
	FullName               string
	Phone                  *string
	Role                   string
	IsActive               bool
	LastLoginAt            *time.Time
	CreatedAt              time.Time
	UpdatedAt              time.Time
	TenantID               uuid.UUID
	TenantCode             string
	TenantLegalName        string
	TenantGs1CompanyPrefix string
	TenantStatus           string
}

func (q *Queries) GetMe(ctx context.Context, id uuid.UUID) (GetMeRow, error) {
	row := q.db.QueryRow(ctx, getMe, id)
	var i GetMeRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FullName,
		&i.Phone,
		&i.Role,
		&i.IsActive,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TenantID,
		&i.TenantCode,
		&i.TenantLegalName,
		&i.TenantGs1CompanyPrefix,
		&i.TenantStatus,
	)
	return i, err
}

const getPasswordHash = `-- name: GetPasswordHash :one
SELECT password_hash
FROM core.users
WHERE id = $1
`

func (q *Queries) GetPasswordHash(ctx context.Context, id uuid.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getPasswordHash, id)
	var password_hash string
	err := row.Scan(&password_hash)
	return password_hash, err
}

const getSessionFamily = `-- name: GetSessionFamily :one
SELECT family_id
FROM core.auth_sessions
WHERE id = $1
`

func (q *Queries) GetSessionFamily(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getSessionFamily, id)
	var family_id uuid.UUID
	err := row.Scan(&family_id)
	return family_id, err
}

const lockSession = `-- name: LockSession :one
SELECT
    id,
    family_id,
    user_id,
    expires_at,
    rotated_at,
    revoked_at
FROM core.auth_sessions
WHERE id = $1
FOR UPDATE
`

type LockSessionRow struct {
	ID        uuid.UUID
	FamilyID  uuid.UUID
	UserID    uuid.UUID
	ExpiresAt time.Time
	RotatedAt *time.Time
	RevokedAt *time.Time
}

func (q *Queries) LockSession(ctx context.Context, id uuid.UUID) (LockSessionRow, error) {
	row := q.db.QueryRow(ctx, lockSession, id)
	var i LockSessionRow
	err := row.Scan(
		&i.ID,
		&i.FamilyID,
		&i.UserID,
		&i.ExpiresAt,
		&i.RotatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const markSessionRotated = `-- name: MarkSessionRotated :exec
UPDATE core.auth_sessions
SET rotated_at = $1
WHERE id = $2
`

type MarkSessionRotatedParams struct {
	RotatedAt *time.Time
	ID        uuid.UUID
}

func (q *Queries) MarkSessionRotated(ctx context.Context, arg MarkSessionRotatedParams) error {
	_, err := q.db.Exec(ctx, markSessionRotated, arg.RotatedAt, arg.ID)
	return err
}

const recordLogin = `-- name: RecordLogin :exec
UPDATE core.users
SET last_login_at = $1
WHERE id = $2
`

type RecordLoginParams struct {
	LoggedInAt *time.Time
	ID         uuid.UUID
}

func (q *Queries) RecordLogin(ctx context.Context, arg RecordLoginParams) error {
	_, err := q.db.Exec(ctx, recordLogin, arg.LoggedInAt, arg.ID)
	return err
}

const revokeOtherUserSessions = `-- name: RevokeOtherUserSessions :exec
UPDATE core.auth_sessions
SET revoked_at = $1
WHERE user_id = $2
  AND family_id <> $3
  AND revoked_at IS NULL
`

type RevokeOtherUserSessionsParams struct {
	RevokedAt    *time.Time
	UserID       uuid.UUID
	KeepFamilyID uuid.UUID
}

func (q *Queries) RevokeOtherUserSessions(ctx context.Context, arg RevokeOtherUserSessionsParams) error {
	_, err := q.db.Exec(ctx, revokeOtherUserSessions, arg.RevokedAt, arg.UserID, arg.KeepFamilyID)
	return err
}

const revokeSessionFamily = `-- name: RevokeSessionFamily :exec
UPDATE core.auth_sessions
SET revoked_at = $1
WHERE family_id = $2
  AND revoked_at IS NULL
`

type RevokeSessionFamilyParams struct {
	RevokedAt *time.Time
	FamilyID  uuid.UUID
}

func (q *Queries) RevokeSessionFamily(ctx context.Context, arg RevokeSessionFamilyParams) error {
	_, err := q.db.Exec(ctx, revokeSessionFamily, arg.RevokedAt, arg.FamilyID)
	return err
}

const setPasswordHash = `-- name: SetPasswordHash :exec
UPDATE core.users
SET password_hash = $1
WHERE id = $2
`

type SetPasswordHashParams struct {
	PasswordHash string
	ID           uuid.UUID
}

func (q *Queries) SetPasswordHash(ctx context.Context, arg SetPasswordHashParams) error {
	_, err := q.db.Exec(ctx, setPasswordHash, arg.PasswordHash, arg.ID)
	return err
}
