// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: inventory.sql

package queries

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/veritrace-platform/core-business-service/internal/calendar"
)

const addToBalance = `-- name: AddToBalance :one
INSERT INTO core.inventory_balances AS b (
    tenant_id,
    location_id,
    lot_id,
    quantity_on_hand
)
VALUES (
    $1,
    $2,
    $3,
    $4
)
ON CONFLICT (location_id, lot_id) DO UPDATE
SET quantity_on_hand = b.quantity_on_hand + excluded.quantity_on_hand
RETURNING quantity_on_hand
`

type AddToBalanceParams struct {
	TenantID   uuid.UUID
	LocationID uuid.UUID
	LotID      uuid.UUID
	Quantity   int32
}

// PostgreSQL checks the proposed row before it looks for a conflict, so only positive quantities take this path.
func (q *Queries) AddToBalance(ctx context.Context, arg AddToBalanceParams) (int32, error) {
	row := q.db.QueryRow(ctx, addToBalance,
		arg.TenantID,
		arg.LocationID,
		arg.LotID,
		arg.Quantity,
	)
	var quantity_on_hand int32
	err := row.Scan(&quantity_on_hand)
	return quantity_on_hand, err
}

const listBalances = `-- name: ListBalances :many
SELECT
    b.location_id,
    l.gln AS location_gln,
    l.name AS location_name,
    b.lot_id,
    t.lot_number,
    t.gtin,
    t.product_name,
    t.expiration_date,
    t.status AS lot_status,
    b.quantity_on_hand,
    b.updated_at
FROM core.inventory_balances b
JOIN core.locations l ON l.id = b.location_id
JOIN core.lots t ON t.id = b.lot_id
WHERE b.quantity_on_hand > 0
  AND ($1::uuid IS NULL OR b.location_id = $1)
  AND ($2::uuid IS NULL OR b.lot_id = $2)
  AND (
      $3::uuid IS NULL
      OR b.location_id < $3
      OR (b.location_id = $3 AND b.lot_id < $4::uuid)
  )
ORDER BY b.location_id DESC, b.lot_id DESC
LIMIT $5
`

type ListBalancesParams struct {
	LocationID      *uuid.UUID
	LotID           *uuid.UUID
	AfterLocationID *uuid.UUID
	AfterLotID      *uuid.UUID
	RowLimit        int32
}

type ListBalancesRow struct {
	LocationID     uuid.UUID
	LocationGln    string
	LocationName   string
	LotID          uuid.UUID
	LotNumber      string
	Gtin           string
	ProductName    string
	ExpirationDate calendar.Date
	LotStatus      string
	QuantityOnHand int32
	UpdatedAt      time.Time
}

func (q *Queries) ListBalances(ctx context.Context, arg ListBalancesParams) ([]ListBalancesRow, error) {
	rows, err := q.db.Query(ctx, listBalances,
		arg.LocationID,
		arg.LotID,
		arg.AfterLocationID,
		arg.AfterLotID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBalancesRow
	for rows.Next() {
		var i ListBalancesRow
		if err := rows.Scan(
			&i.LocationID,
			&i.LocationGln,
			&i.LocationName,
			&i.LotID,
			&i.LotNumber,
			&i.Gtin,
			&i.ProductName,
			&i.ExpirationDate,
			&i.LotStatus,
			&i.QuantityOnHand,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordMovement = `-- name: RecordMovement :exec
INSERT INTO core.inventory_movements (
    tenant_id,
    location_id,
    lot_id,
    quantity_delta,
    reason,
    shipment_id,
    created_by
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
)
`

type RecordMovementParams struct {
	TenantID      uuid.UUID
	LocationID    uuid.UUID
	LotID         uuid.UUID
	QuantityDelta int32
	Reason        string
	ShipmentID    *uuid.UUID
	CreatedBy     uuid.UUID
}

func (q *Queries) RecordMovement(ctx context.Context, arg RecordMovementParams) error {
	_, err := q.db.Exec(ctx, recordMovement,
		arg.TenantID,
		arg.LocationID,
		arg.LotID,
		arg.QuantityDelta,
		arg.Reason,
		arg.ShipmentID,
		arg.CreatedBy,
	)
	return err
}

const takeFromBalance = `-- name: TakeFromBalance :one
UPDATE core.inventory_balances
SET quantity_on_hand = quantity_on_hand - $1
WHERE location_id = $2
  AND lot_id = $3
RETURNING quantity_on_hand
`

type TakeFromBalanceParams struct {
	Quantity   int32
	LocationID uuid.UUID
	LotID      uuid.UUID
}

func (q *Queries) TakeFromBalance(ctx context.Context, arg TakeFromBalanceParams) (int32, error) {
	row := q.db.QueryRow(ctx, takeFromBalance, arg.Quantity, arg.LocationID, arg.LotID)
	var quantity_on_hand int32
	err := row.Scan(&quantity_on_hand)
	return quantity_on_hand, err
}
