// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: directory.sql

package queries

import (
	"context"

	"github.com/google/uuid"
)

const lookupLocationByGLN = `-- name: LookupLocationByGLN :one
SELECT
    gln,
    name,
    address,
    city,
    country_code,
    latitude,
    longitude,
    geo_fence_radius_meters,
    tenant_id,
    tenant_code,
    tenant_legal_name
FROM core.lookup_location_by_gln($1)
`

type LookupLocationByGLNRow struct {
	Gln                  *string
	Name                 *string
	Address              *string
	City                 *string
	CountryCode          *string
	Latitude             *float64
	Longitude            *float64
	GeoFenceRadiusMeters *int32
	TenantID             *uuid.UUID
	TenantCode           *string
	TenantLegalName      *string
}

func (q *Queries) LookupLocationByGLN(ctx context.Context, gln string) (LookupLocationByGLNRow, error) {
	row := q.db.QueryRow(ctx, lookupLocationByGLN, gln)
	var i LookupLocationByGLNRow
	err := row.Scan(
		&i.Gln,
		&i.Name,
		&i.Address,
		&i.City,
		&i.CountryCode,
		&i.Latitude,
		&i.Longitude,
		&i.GeoFenceRadiusMeters,
		&i.TenantID,
		&i.TenantCode,
		&i.TenantLegalName,
	)
	return i, err
}

const lookupTenantByCode = `-- name: LookupTenantByCode :one
SELECT
    tenant_id,
    code,
    legal_name
FROM core.lookup_tenant_by_code($1)
`

type LookupTenantByCodeRow struct {
	TenantID  *uuid.UUID
	Code      *string
	LegalName *string
}

func (q *Queries) LookupTenantByCode(ctx context.Context, code string) (LookupTenantByCodeRow, error) {
	row := q.db.QueryRow(ctx, lookupTenantByCode, code)
	var i LookupTenantByCodeRow
	err := row.Scan(&i.TenantID, &i.Code, &i.LegalName)
	return i, err
}
