// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tenants.sql

package queries

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const registerTenant = `-- name: RegisterTenant :one
SELECT
    tenant_id,
    headquarters_location_id,
    admin_user_id,
    created_at
FROM core.register_tenant(
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13,
    $14,
    $15,
    $16
)
`

type RegisterTenantParams struct {
	Code                             string
	LegalName                        string
	TaxCode                          string
	Gs1CompanyPrefix                 string
	HeadquartersGln                  string
	HeadquartersName                 string
	HeadquartersAddress              string
	HeadquartersCity                 string
	HeadquartersCountryCode          string
	HeadquartersLatitude             pgtype.Numeric
	HeadquartersLongitude            pgtype.Numeric
	HeadquartersGeoFenceRadiusMeters int32
	AdminEmail                       string
	AdminPasswordHash                string
	AdminFullName                    string
	AdminPhone                       *string
}

type RegisterTenantRow struct {
	TenantID               *uuid.UUID
	HeadquartersLocationID *uuid.UUID
	AdminUserID            *uuid.UUID
	CreatedAt              *time.Time
}

func (q *Queries) RegisterTenant(ctx context.Context, arg RegisterTenantParams) (RegisterTenantRow, error) {
	row := q.db.QueryRow(ctx, registerTenant,
		arg.Code,
		arg.LegalName,
		arg.TaxCode,
		arg.Gs1CompanyPrefix,
		arg.HeadquartersGln,
		arg.HeadquartersName,
		arg.HeadquartersAddress,
		arg.HeadquartersCity,
		arg.HeadquartersCountryCode,
		arg.HeadquartersLatitude,
		arg.HeadquartersLongitude,
		arg.HeadquartersGeoFenceRadiusMeters,
		arg.AdminEmail,
		arg.AdminPasswordHash,
		arg.AdminFullName,
		arg.AdminPhone,
	)
	var i RegisterTenantRow
	err := row.Scan(
		&i.TenantID,
		&i.HeadquartersLocationID,
		&i.AdminUserID,
		&i.CreatedAt,
	)
	return i, err
}
