// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: locations.sql

package queries

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createLocation = `-- name: CreateLocation :one
INSERT INTO core.locations (
    tenant_id,
    gln,
    name,
    address,
    city,
    country_code,
    latitude,
    longitude,
    geo_fence_radius_meters
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9
)
RETURNING
    id,
    gln,
    name,
    address,
    city,
    country_code,
    latitude,
    longitude,
    geo_fence_radius_meters,
    is_headquarters,
    is_active,
    created_at,
    updated_at
`

type CreateLocationParams struct {
	TenantID             uuid.UUID
	Gln                  string
	Name                 string
	Address              string
	City                 string
	CountryCode          string
	Latitude             float64
	Longitude            float64
	GeoFenceRadiusMeters int32
}

type CreateLocationRow struct {
	ID                   uuid.UUID
	Gln                  string
	Name                 string
	Address              string
	City                 string
	CountryCode          string
	Latitude             float64
	Longitude            float64
	GeoFenceRadiusMeters int32
	IsHeadquarters       bool
	IsActive             bool
	CreatedAt            time.Time
	UpdatedAt            time.Time
}

func (q *Queries) CreateLocation(ctx context.Context, arg CreateLocationParams) (CreateLocationRow, error) {
	row := q.db.QueryRow(ctx, createLocation,
		arg.TenantID,
		arg.Gln,
		arg.Name,
		arg.Address,
		arg.City,
		arg.CountryCode,
		arg.Latitude,
		arg.Longitude,
		arg.GeoFenceRadiusMeters,
	)
	var i CreateLocationRow
	err := row.Scan(
		&i.ID,
		&i.Gln,
		&i.Name,
		&i.Address,
		&i.City,
		&i.CountryCode,
		&i.Latitude,
		&i.Longitude,
		&i.GeoFenceRadiusMeters,
		&i.IsHeadquarters,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCompanyPrefix = `-- name: GetCompanyPrefix :one
SELECT gs1_company_prefix
FROM core.tenants
WHERE id = $1
`

func (q *Queries) GetCompanyPrefix(ctx context.Context, id uuid.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getCompanyPrefix, id)
	var gs1_company_prefix string
	err := row.Scan(&gs1_company_prefix)
	return gs1_company_prefix, err
}

const getLocation = `-- name: GetLocation :one
SELECT
    id,
    gln,
    name,
    address,
    city,
    country_code,
    latitude,
    longitude,
    geo_fence_radius_meters,
    is_headquarters,
    is_active,
    created_at,
    updated_at
FROM core.locations
WHERE id = $1
`

type GetLocationRow struct {
	ID                   uuid.UUID
	Gln                  string
	Name                 string
	Address              string
	City                 string
	CountryCode          string
	Latitude             float64
	Longitude            float64
	GeoFenceRadiusMeters int32
	IsHeadquarters       bool
	IsActive             bool
	CreatedAt            time.Time
	UpdatedAt            time.Time
}

func (q *Queries) GetLocation(ctx context.Context, id uuid.UUID) (GetLocationRow, error) {
	row := q.db.QueryRow(ctx, getLocation, id)
	var i GetLocationRow
	err := row.Scan(
		&i.ID,
		&i.Gln,
		&i.Name,
		&i.Address,
		&i.City,
		&i.CountryCode,
		&i.Latitude,
		&i.Longitude,
		&i.GeoFenceRadiusMeters,
		&i.IsHeadquarters,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listLocations = `-- name: ListLocations :many
SELECT
    id,
    gln,
    name,
    address,
    city,
    country_code,
    latitude,
    longitude,
    geo_fence_radius_meters,
    is_headquarters,
    is_active,
    created_at,
    updated_at
FROM core.locations
WHERE ($1::boolean IS NULL OR is_active = $1)
  AND ($2::uuid IS NULL OR id < $2)
ORDER BY id DESC
LIMIT $3
`

type ListLocationsParams struct {
	IsActive *bool
	After    *uuid.UUID
	RowLimit int32
}

type ListLocationsRow struct {
	ID                   uuid.UUID
	Gln                  string
	Name                 string
	Address              string
	City                 string
	CountryCode          string
	Latitude             float64
	Longitude            float64
	GeoFenceRadiusMeters int32
	IsHeadquarters       bool
	IsActive             bool
	CreatedAt            time.Time
	UpdatedAt            time.Time
}

func (q *Queries) ListLocations(ctx context.Context, arg ListLocationsParams) ([]ListLocationsRow, error) {
	rows, err := q.db.Query(ctx, listLocations, arg.IsActive, arg.After, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLocationsRow
	for rows.Next() {
		var i ListLocationsRow
		if err := rows.Scan(
			&i.ID,
			&i.Gln,
			&i.Name,
			&i.Address,
			&i.City,
			&i.CountryCode,
			&i.Latitude,
			&i.Longitude,
			&i.GeoFenceRadiusMeters,
			&i.IsHeadquarters,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLocation = `-- name: UpdateLocation :one
UPDATE core.locations
SET name = coalesce($1, name),
    address = coalesce($2, address),
    city = coalesce($3, city),
    country_code = coalesce($4, country_code),
    latitude = coalesce($5, latitude),
    longitude = coalesce($6, longitude),
    geo_fence_radius_meters = coalesce($7, geo_fence_radius_meters),
    is_active = coalesce($8, is_active)
WHERE id = $9
RETURNING
    id,
    gln,
    name,
    address,
    city,
    country_code,
    latitude,
    longitude,
    geo_fence_radius_meters,
    is_headquarters,
    is_active,
    created_at,
    updated_at
`

type UpdateLocationParams struct {
	Name                 *string
	Address              *string
	City                 *string
	CountryCode          *string
	Latitude             *float64
	Longitude            *float64
	GeoFenceRadiusMeters *int32
	IsActive             *bool
	ID                   uuid.UUID
}

type UpdateLocationRow struct {
	ID                   uuid.UUID
	Gln                  string
	Name                 string
	Address              string
	City                 string
	CountryCode          string
	Latitude             float64
	Longitude            float64
	GeoFenceRadiusMeters int32
	IsHeadquarters       bool
	IsActive             bool
	CreatedAt            time.Time
	UpdatedAt            time.Time
}

func (q *Queries) UpdateLocation(ctx context.Context, arg UpdateLocationParams) (UpdateLocationRow, error) {
	row := q.db.QueryRow(ctx, updateLocation,
		arg.Name,
		arg.Address,
		arg.City,
		arg.CountryCode,
		arg.Latitude,
		arg.Longitude,
		arg.GeoFenceRadiusMeters,
		arg.IsActive,
		arg.ID,
	)
	var i UpdateLocationRow
	err := row.Scan(
		&i.ID,
		&i.Gln,
		&i.Name,
		&i.Address,
		&i.City,
		&i.CountryCode,
		&i.Latitude,
		&i.Longitude,
		&i.GeoFenceRadiusMeters,
		&i.IsHeadquarters,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
